title: CM5 FOREVER
description: The showcase website for the CM5 FOREVER community.
author: Matiboux
discord:
  id: 298392798607179777
  link: https://discord.gg/jAZabyg
links:
  twitter: https://twitter.com/Cm5Forever
  facebook: https://www.facebook.com/Cmieuxa5YT
  youtube: https://www.youtube.com/c/Cestmieuxa5Officiel
  twitch: https://www.twitch.tv/cm5tv
  streamlabs: https://streamlabs.com/cm5tv
  paypal:
    pools:
      community: https://www.paypal.com/pools/c/8ai4n4qymX
      association: https://www.paypal.com/pools/c/8m0Z8vnqnU
